title: 김지섭 블로그
description: 위키, 넓혀라 기술 스택
author: jisobkim
profile: /static/img/profile_2020.jpg
github: https://github.com/jisobkim
mail: jisobkim@gmail.com
about: Node.js React 개발하고 있습니다. 영상서비스, 프론트엔드 중점으로 개발하고 있습니다. 
disqus_shortname: jisobkim
google_analytics: UA-102579338-1

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/jisobkim"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jisobkim/"
    - icon: fa-github
      link: "https://github.com/jisobkim"
    - icon: fa-rss
      link: "/feed.xml"

share:
  twitter_username: jisobkim
  fb_appid: 471363289889856

urls:
    - text: Categories
      url: /category
    - text: Blog
      url: /blog

url: "https://jisobkim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
